apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-community-store
  name: fdk-community-store
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-community-store
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-community-store
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: fdk-community-store-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_COMMUNITY_STORE_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fdk-community-store-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_COMMUNITY_STORE_PASSWORD
        image: {{ required "Missing value FDK_COMMUNITY_STORE_IMAGE" .Values.FDK_COMMUNITY_STORE_IMAGE }}
        imagePullPolicy: Always
        name: fdk-community-store
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: {{ required "Missing value FDK_COMMUNITY_STORE_MEMORY" .Values.FDK_COMMUNITY_STORE_MEMORY | quote }}
        volumeMounts:
        - mountPath: /data/db/
          name: fdk-community-store-claim0
      restartPolicy: Always
      volumes:
      - name: fdk-community-store-claim0
        persistentVolumeClaim:
          claimName: fdk-community-store-claim0
status: {}
