apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-community-store
  name: fdk-community-store
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    fdk.service: fdk-community-store
status:
  loadBalancer: {}
